{
 "title": "empty_loki",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "direction": "backward" }
   ]
  },
  {
   "title": "Zugriffs-Logs aus NGINX (auth.lua)",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"nginx\"}"
    }
   ]
  },
  {
   "title": "Anzahl Zugriffe (letzte 5 Minuten)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"nginx\"}[5m])"
    }
   ]
  },
  {
   "title": "Zeitverlauf: Anzahl Zugriffe (pro 30s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "count_over_time({job=\"nginx\"}[30s])"
    }
   ]
  }
 ]
}